[server]
headless = true
runOnSave = true

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#0f766e"
backgroundColor = "#f7fafc"
secondaryBackgroundColor = "#e6fffa"
textColor = "#0f172a"
